version: '2'
services:
  php:
    container_name: yii2-skeleton-app
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '${DOCKER_APP_PORT}:80'